# Generated by Django 3.2.8 on 2021-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='courseNum',
            field=models.IntegerField(unique=True),
        ),
    ]
